environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36-x64"
platform:
  - x64
install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install pipenv pip --upgrade
  - pipenv install --dev --system --skip-lock
build_script:
  - pytest
  - python setup.py bdist_wheel
