name: numpy_indexed
channels:
  - anaconda
  - clinicalgraphics
dependencies:
  - python =3.5*
  - numpy =1.10*
  - future =0.15*
  # dev
  - jupyter =1.0*
  - notebook =4.0*
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  # tests
  - pytest >=2.8.4,<2.9
  - matplotlib >=1.4.3,<1.6
  - scipy
  # docs
  - sphinx >=1.3.1,<1.4
