name: numpy_tools
channels:
  - anaconda
dependencies:
  - python
  - numpy =1.10*
  - matplotlib >=1.4.3,<1.6
  - future =0.15*
  # dev
  - jupyter =1.0*
  - notebook =4.0*
  - anaconda-client >=1.2.1,<1.3
  - invoke >=0.11.1,<0.12
  # linting
  - flake8 =2.3*
  - flake8-future-import >=0.3.2,<0.4
  - pep8-naming >=0.3.3,<0.4
  - flake8-docstrings >=0.2.4,<0.3
  # tests
  - pytest >=2.8.4,<2.9
  - mock =1.3*
  - pytest-mock =0.10*
  - pytest-cov =2.2.1
  # docs
  - sphinx >=1.3.1,<1.4
  - numpydoc =0.6*
