name: numpy_indexed
channels:
  - anaconda
  - clinicalgraphics
  - janschulz
dependencies:
  - python
  - numpy
  - future
  # dev
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  - pypandoc
  # tests
  - pytest >=2.8.4,<2.9

# only required to run some of the examples
#  - matplotlib >=1.4.3,<1.6
#  - scipy
