name: numpy_indexed
channels:
  - anaconda
  - clinicalgraphics
dependencies:
  - python =3.5*
  - numpy =1.10*
  - future =0.15*
  # dev
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  # tests
  - pytest >=2.8.4,<2.9

# only required to run the examples
#  - matplotlib >=1.4.3,<1.6
#  - scipy
