about:
  home: https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP
  license: Freely Distributable
  summary: Numpy indexing based extensions
build:
  number: 4
package:
  name: numpy-indexed
  version: 0.1.2
requirements:
  build:
  - python
  - numpy
  - pyyaml =3.11*
  - future 0.15*
  run:
  - python
  - numpy
  - future 0.15*
source:
  path: ..
test:
  commands:
  - py.test
  imports:
  - numpy_indexed
  requires:
  - pytest >=2.8.4,<2.9
