package:
  name: numpy-indexed
  version: 0.3.4
source:
  path: ..
build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 2
requirements:
  build:
  - python
  run:
  - python
  - numpy
  - future
test:
  imports:
  - numpy_indexed
about:
  home: https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP
  license: Freely Distributable
  summary: This package contains functionality for indexed operations on numpy ndarrays, providing efficient vectorized functionality such as grouping and set operations.
